### ISSUE TITLE
Arch春合宿

### ISSUE THREAD

**Issue by seibe** [sfc-arch/meeting#7]
有志で、どこか旅にでも出ましょう。
そしてコーティングしよう。

**Comment by seibe** [comment]
希望する場所があれば、こちらでスケジュール調整しちゃうよ。
内容もノープランなので募集。（ex. 雪山コーディング、温泉でORF展示の企画会議、露天風呂でドローン飛ばす）

**Comment by miyukki** [comment]
もくもく開発したい

**Comment by demmys** [comment]
+ Arch Webサイト実装
+ Hubotに新機能追加ハッカソン
+ ORF展示案アイディア出し
+ Vimプラグイン実装

**Comment by kut2uky** [comment]
(どこ行ってもVim関連のことやりそう…)

**Comment by seibe** [comment]
+ 新言語勉強会 (Rustやりたいだけ)

**Comment by demmys** [comment]
小学校の修学旅行のしおりに国語の勉強と称して短歌を各ページがあったのを思い出した。
代わりにアセンブラ短歌を…

**Comment by miyukki** [comment]
各自やりたいことやったりして進捗を昼よる共有するとか

**Comment by shunkino** [comment]
優良ジャンク探しの旅したい・・・

**Comment by demmys** [comment]
発表が終わった時に誰も動かなかったら流れそうなので @seibe をAssignしてみた。

**Comment by seibe** [comment]
意地でも流さんよ :)

**Comment by demmys** [comment]
@seibe 結局これどうなってるんだ

**Comment by seibe** [comment]
@各位 候補地と予算のリストを作成中です！　お待たせしてすんません。
なお、3月下旬で調整してますます。

**Comment by miyukki** [comment]
（ほ、本格的だ…

**Comment by gucchan22** [comment]
帰りの飛行機が3月ごろになると非常に取れにくいのでできれば日程をはやめに教えていただけるとうれしい....かも

**Comment by seibe** [comment]
@gucchan22 了解です。では日程だけ明日中に決めちゃいます。
